services:
  - type: web
    name: health-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MODEL_NAME
        value: llama3-8b-8192
      - key: PROVIDER
        value: groq
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
